### PR TITLE
Google and Letterboxd support

### PR DESCRIPTION
**Pull request by mofman**

### CODE REVIEW

**Comment by SpaceK33z** [comment]
Ah, I know why it can't find the movies on Plex for Letterboxd. They use a special space character instead of a "normal" space. The query is this `?query=Being%20John%C2%A0Malkovich` while it should be `?query=Being%20John%20Malkovich`.

I've fixed this in `master`, see db59b00118a0e309766f13e9ae15ada95ecdbdc2.

**Comment by mofman** [comment]
Good eye! Sweet, those seems to be working okay but feel free to refactor as much as you want.

They still need styling which might be best for you to do as I'm not great at front end. 
Also need to match all google domains in the manifest.json, https://www.google.*/* seems to fail?

**Comment by SpaceK33z** [comment]
Allright I'll do the styling. It can take some time before I get to it though.

About the google domains thingy, it seems like Chrome doesn't want to make a feature to make it easy to match all those domains. See [this issue](https://bugs.chromium.org/p/chromium/issues/detail?id=18259#c9) and [this one](https://bugs.chromium.org/p/chromium/issues/detail?id=403422).

**Comment by SpaceK33z** [comment]
@mofman a full year later and I finally implemented Letterboxd support based on your PR 😶. I couldn't merge the full PR because the Google functionality is not ready yet. But thanks, this really saved much time! I only had to tweak some small things, mostly styling.

**Comment by Ephellon** [comment]
I've added your changes to the 4.0 update @mofman 🥇

**Comment by mofman** [comment]
nice work @Ephellon & @SpaceK33z!

**Pull request closed without merging**
