### PR TITLE
Upgrade to v4.1

### LINKED ISSUE #61: Remove Plex login requirement
Suggested by @bolhaskutya in #56:
> I only want to use the addon to send to radarr

This would require a slight overhaul, as the code is designed to search Plex for matching media... Maybe a dummy machineID can be used, as long as they have a Plex account?

### LINKED ISSUE #64: Mixed Content Error (HTTPS/HTTP)
I downloaded and installed v4 and I got this error. 
err

If I choose to load unsafe script, it works fine.

### PR DESCRIPTION
**Pull request by Ephellon**
# Planned release date: *December 2018*

Date (MM/DD/YYYY) | With Debugging | Without Debugging | Commit URL | Notes
| ---- | ---- | ---- | ---- | ----
12/23/2018 - **2** | [#8e9db12.zip](https://github.com/SpaceK33z/web-to-plex/files/2706316/src.zip) | [8e9db12.zip](https://github.com/SpaceK33z/web-to-plex/files/2706317/src.zip) | 8e9db12e3229ba089c4a31b4fa75e5920899c3bf | Fixed a few major bugs
12/23/2018 - **1** | [#1588d65.zip](https://github.com/SpaceK33z/web-to-plex/files/2705814/src.zip) | [1588d65.zip](https://github.com/SpaceK33z/web-to-plex/files/2705813/src.zip) | 1588d650b41f91db6efb26a1653d3408363e0921 | Fixes a minor bug on the options page
12/20/2018 - **4** | [#13de039.zip](https://github.com/SpaceK33z/web-to-plex/files/2701505/src.zip) | [13de039.zip](https://github.com/SpaceK33z/web-to-plex/files/2701518/src.zip) | 13de0391fa7e80217cbd14de3e3bf5e72b48a2f2 | Added support for Flickmetrix/Cinesift ([#62@447677855](https://github.com/SpaceK33z/web-to-plex/issues/62#issuecomment-447677855))
12/20/2018 - **3** | [#349bea1.zip](https://github.com/SpaceK33z/web-to-plex/files/2700728/src.zip) | [349bea1.zip](https://github.com/SpaceK33z/web-to-plex/files/2700735/src.zip) | 349bea122b804a3cd376954e6d258e8edd9bb54b | Added the advance Proxy settings
12/20/2018 - **2** | [#25ad8e8.zip](https://github.com/SpaceK33z/web-to-plex/files/2700499/src.zip) | [25ad8e8.zip](https://github.com/SpaceK33z/web-to-plex/files/2700567/src.zip) | 25ad8e870404398ad60de4240af44e70f0f44c5b | Added the Proxy settings
12/20/2018 - **1** | [#2786b56.zip](https://github.com/SpaceK33z/web-to-plex/files/2698093/src.zip) | [2786b56.zip](https://github.com/SpaceK33z/web-to-plex/files/2698092/src.zip) | 2786b5653b86a59e7ca4916820276d967e8a90ac | Added movie support for VRV
12/19/2018 - **3** | [#80402f1.zip](https://github.com/SpaceK33z/web-to-plex/files/2697534/src.zip) | [80402f1.zip](https://github.com/SpaceK33z/web-to-plex/files/2697533/src.zip) | 80402f11d7bfe0eed585353ea60805df66e9c07c | Fixes `tvdb.js` error, and hover effect bug
12/19/2018 - **2** | [#a97b12d.zip](https://github.com/SpaceK33z/web-to-plex/files/2697155/src.zip) | [a97b12d.zip](https://github.com/SpaceK33z/web-to-plex/files/2697154/src.zip) | a97b12dbef4a5aada47725c78b2eb60103a12189 | Fixes #64
12/19/2018 - **1** | [#133baeb.zip](https://github.com/SpaceK33z/web-to-plex/files/2696685/src.zip) | [133baeb.zip](https://github.com/SpaceK33z/web-to-plex/files/2696717/src.zip) | 133baebed2543ba05cc063248d10e86010daa6ab | Fixes #61, and [#62@447651064](https://github.com/SpaceK33z/web-to-plex/issues/62#issuecomment-447651064)

### CODE REVIEW

**Comment by SpaceK33z** [comment]
I have some time the next few days so I want to finally release the extension to the Play Store and Mozilla store, since that still hasn't happened.

However I don't fully understand the current state of this PR. It has a lot of merge conflicts.

**Comment by Ephellon** [comment]
Hi @SpaceK33z, I don't have anything else to add to v4.1, though I still am running tests; but the current commit (df5362b78b79537ee159cc6013026f51b2ed16f6) is stable enough for realease.

> It has alot of merge conflicts.
- I've gone through each on Atom (by GitHub), but there aren't any conflicts... I'll attach a ZIP so that you can merge the changes without the PR (please close it if you feel it's no longer applicable).
- Also, please provide a list of files you **need to never change**, these are files I won't change:
  - .editorconfig
  - .eslintrc
  - .gitignore
  - LICENSE
  - Makefile
  - env.example
  - package.json
  - **yarn.lock** (auto-gen)
  - *Add more file names if needed*

**Comment by Ephellon** [comment]
@SpaceK33z, one thing just occurred to me with the page styling&mdash;I'm not able to test it on Firefox, so that could be an issue. I made the CSS as strict as possible (using `!important`), but it's not the same as Chrome&mdash;some elements would stop rendering with certain attributes using `!important`, especially on Flickmetrix. For example, when the prompt shows on Flickmetrix, I'm not allowed to change the `H1` background (`"Approve X items"`), as it stops rendering, and is overridden by another `!important` further down (more strict somehow).

That's all I can think of at the moment that would be a problem.

**Comment by Ephellon** [comment]
Making one more change, then I'll be done

**Comment by Ephellon** [comment]
All done @SpaceK33z, please see [8e9db12.zip](https://github.com/SpaceK33z/web-to-plex/files/2706317/src.zip) (no debugging), and/or [#8e9db12.zip](https://github.com/SpaceK33z/web-to-plex/files/2706316/src.zip) (debugging)

**Pull request merged**
