### PR TITLE
Upgrade to v4 (rebased)

### PR DESCRIPTION
**Pull request by Ephellon**
Rebased from @SpaceK33z

### CODE REVIEW

**Comment by Ephellon** [comment]
Fixing a few more errors (e.g. TVDb airdate error), will send an update soon and include a change.log (text) file.

**Comment by SpaceK33z** [comment]
Okay cool! Haven't had the time to look more at the code yet. Could you include the changelog here instead of in the repository? Because I'm writing the changelog using GitHub releases: https://github.com/SpaceK33z/web-to-plex/releases

I've also added you as collaborator now! After your fixes we can merge it, we'll go through a "beta" process where we'll test everything a last time and then finally release it.

**Comment by Ephellon** [comment]
Cool, no problem; I'll make it GitHub MD flavor

**Comment by Ephellon** [comment]
# NOTES

- **Bolded items** are deemed the most significant, such as added sites and new features

# TODO

- Use the "download" API to save files (i.e. Flenix's "Save As" option for non-Flenix domains)

# CHANGELOG (Oldest to Newest)

### v0.1 / SpaceK33z@9e81a0cf17e165a0850cfcdfdfa0d4b674dbfb6b

- Removed CouchPotato settings as they were unused (later redacted: v0.2.2.0)
- **Added Flenix as a supported site**

### v0.2 / SpaceK33z@f3564c87241265a7913c043d0aa0e11cbff7c2c3

- Fixed Flenix downloading bug
- Updated button style (Flenix only)
- Began versioning at 0.2

### v0.2.0.1 / SpaceK33z@f3b9b52408d360e24263df1a5a22c86d6197f585

- **Added the "Download File" dialog (later change to "Save File")**

### v0.2.1.2 / SpaceK33z@b4c8d89e6c8fd123ff68be262ab1e2503af4ae09

- Added multiple button locations to Flenix (later redacted: v3.0.0.0)
- **Added Web to Plex logos**
- Restructured file layout

### v0.2.1.3 / SpaceK33z@aa3a731f2ad46d5850d1574e0143f40546da7892

- Created a Plex-like UI/UX and updated button styles
    - **includes the pop-up feature**

### v0.2.2.0 / SpaceK33z@f1760423aebc3ed7fee15ec0f50d96eee3be41f8

- Fixed an adding error for Radarr and Sonarr
- Updated UI/UX
    - **Adapted the "Plex Token Login" feature**
- Restructured code layout (camel-cased variable names, and made more readable)

## v0.3.0.0 / SpaceK33z@25bffc874cfab84d95216cda48d1e97eaa360776

- **Added TV Maze as a supported site**
- Fixed Sonarr adding error
- Updated site scripts

## v0.3.0.1 / SpaceK33z@3196f6dbe3a3413b1fe8a9f10a2abe563853c99d

- Updated UX: allowed site scripts to access image files (as action buttons)
- **Added API support for finding movie/series IDs (The Movie DB, and The TV DB)**

## v0.3.3.0 / SpaceK33z@dba19e0b27c3815c66a7f18a7b323ea39c367c64

- **Added The TV Database as a supported site, as well as: The Movie Database and VRV**

## v0.3.3.1 / SpaceK33z@62dbb8eab84dc0765c3f2448bfc3eb1ecbe2b63f

- Fixed an adding error

## v0.4.0.0 / SpaceK33z@dce5467cd396c3086a1116af4feb24053880c8fd

- **Added Plex login support (username / password), see commit SpaceK33z@db01d1a83d32e4d73f2ea671f634e6cc5b4c0fe7**

## v0.5.0.0 / SpaceK33z@ed1033f330782328f2884b00923f166b74808c37

- **Added Hulu as a supported site, as well as: Google Play Store**

## v0.5.0.2 / SpaceK33z@7bf755504a4ead8d832e88ce4272f1b896374333

- **Included the "Storage Path" feature, see commit SpaceK33z@27506b9a4c12496bd7aad6ee09deb8a5b9418cac**

## v0.5.1.0 / SpaceK33z@e8609920e3b2005d8979a0df16b8a309a9221a32

- **Removed Firefox support**
- Added multiple Flenix domains

## v1.0.0.0 / SpaceK33z@b05ebfa7230810cb30ca39f72613b2ef7409e4f0

- Restructured file layout

## v1.0.1.0 / SpaceK33z@cc557ca0ab76788a0fe5286d43ade43de0de5209

- **Added iTunes as a supported site, as well as: Fandango, and Metacritic**

## v1.0.2.0 / SpaceK33z@250dbbe02be7cd3d60ad37538bb7e63acf78bbbf

- **Added Amazon as a supported site, as well as: Verizon, and Vudu**

----

## v1.1.0.0 / SpaceK33z@a321795c6fdf6917542d56f2a45301cd326191c6

- **Added The Movide DB as a search source for Plex, Radarr, and Sonarr**

## v1.1.1.0 / SpaceK33z@93a79bdb04b0ad43c37538cc25042d9bbfefd642

- Utilized the scoring feature for The TV DB

## v1.1.0.2 / SpaceK33z@9879cf8c75a5688985b86be5d37460ab456f0dca

- Added the icon script to the pop-up feature (descriptions on-hover)
- **Added more sites as API lookups (later revised: v1.2.1.5)**

## v1.1.2.0 / SpaceK33z@b3ee310b589a7c04cbdf3c548932a17d0fc1647a

- Added CORS for API lookup sites (Apache)
- Fixed adding errors for Sonarr and Radarr

## v1.2.0.0 / SpaceK33z@fcac789cf1eba7a4dde8288b7c0e7d55ed9ccc1b

- Added badge support to the icon
- **Added the context menu feature (searches)**
- Fixed styling errors
- Fixed bugs for Flenix, Vudu, and Verizon

## v1.2.1.0 / SpaceK33z@afdeb4052ae277bc0d1d4e1f0b5bc26fb0fc3473

- **Added CouchPotato as a supported site, as well as: Rotten Tomatoes**

## v1.2.1.1 / SpaceK33z@6fafb8c9f2a4301926cf082537a4d26e8d549330

- Fixed minor CouchPotato and Letterboxd bugs (no IMDb ID)

## v1.2.1.2 / SpaceK33z@c7cac01aa3cd0fc25967181c1788b8b3f5d3d463

- **Added the "re-search" feature for alternative lookups**
    - if the search failed the first time, use a different site to search again
- **Added button location images**

## v1.2.1.3 / SpaceK33z@4cf196feeac297c341bca075023b64b09c71a676

- Fixed an adding error

## v1.2.1.4 / SpaceK33z@f705e7af667229c1eb7b29608ad6adbb28994aa4

- Updated Amazon to match site changes

## v1.2.1.5 / SpaceK33z@e4ae523b888b3ce35cc969a4ff62769b2599f42e

- **Replaced the Apache API with the Open Movie DB**

## v1.2.1.7 / SpaceK33z@53c8d5b917f040621202e84c3ad2132c22db3e2e

- **Added the "extra API keys" feature**
- **Added ShowRSS as a supported site**
- **Added the "Save Media Info" feature (to speed up repetitive searches; later revised: v1.3.0.0)**

## v1.3.0.0 / SpaceK33z@2aa9695c06decf1b783408f33f5db46cc4bd5b3b

- Began using `sessionStorage` before `localStorage` when saving media info
- Made changes to how the plugin finds movies

## v2.0.0.0 / SpaceK33z@b28951d45f17efc609f2fda5a281193e2c17b613

- **Updated code to be scope dependent**
- **Made other changes to make the plugin P.R. ready, see issue #53**
- **Added the "Plex URL" feature**

----

## v2.0.1.0 / SpaceK33z@817a7f38680a045f8c688fd357b241b3f811d36c

- **Removed manager requirement (Options | Managers)**
    - unintentional feature; would force the user to have at least one valid manager

## v3.0.0.0 / unreleased

- Made numerous changes as a BETA for v4 (explained below)

- Created /change.log
    - used in order to keep up with version changes more easily
- **Removed strict equality for item searches: /utils.js**
    - equality tests for the IDs (IMDb, TVDb, & TMDb) were strict and unpredictable (Number vs. String) and was therefore "dumbed" down to reduce errors
- Fixed The TV DB error: no air date when series' air date is the current month and year (e.g. Aug 2018 for "Insatiable")
    - the `o.first_airdate` property was undefined and would cause a Type error when the airdate was the current month and year
- Changed the color of the version number on the Option's page (for better readability)
    - was grey and blended in; changed to white
- **Changed "Save As..." to ignore unidentified movies (e.g. no ID, but still able to save the file)**
    - movies saved via direct links (i.e. Flenix) would fail without an ID--the user probably doesn't care and jsut wants the movie
- Removed extra Flenix buttons (got too complicated); but left the skeleton for extra buttons for future usage
    - the last button was ugly and discolored; plus Flenix added more buttons, so I just left the top button

**Comment by Ephellon** [comment]
@SpaceK33z, I think it's ready for your review. Let me know when you're ready (@ me so I get a notification please).

**Comment by Ephellon** [comment]
Alrighty--all caught up on notable issues/tickets. And made some bug-runs. v3.1/B is ready.

**Comment by SpaceK33z** [comment]
I want to try it out soon but I have to find some time. Maybe tonight. Sorry!

**Comment by Ephellon** [comment]
OK, I'm making a few more small changes to the `String..toCaps` method. I'll push v3.1.1.1 in about 30 minutes.

**Pull request merged**
